global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'forensics-platform-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['forensics-api:8000']
